### PR TITLE
index: don't wrap around

### LINKED ISSUE #45: Query.index returns the wrong element instead of failing if the index is too large
Example: https://ellie-app.com/jMLjSSNbBa1/0

```elm
import Html exposing (Html, text)
import Html.Attributes exposing (class)
import Test.Html.Query as Query
import Test.Html.Selector as Selector
import Test.Runner


html : Html msg
html =
    Html.div []
        [ Html.div [ class "a" ] [ text "0" ]
        , Html.div [ class "a" ] [ text "1" ]
        , Html.div [ class "a" ] [ text "2" ]
        ]


main : Html msg
main =
    html
        |> Query.fromHtml
        |> Query.findAll [ Selector.class "a" ]
        |> Query.index 3
        |> Query.has [ Selector.text "3" ]
        |> Test.Runner.getFailureReason
        |> Maybe.map .description
        |> Maybe.withDefault "PASSED"
        |> text
        |> List.singleton
        |> Html.pre []
```

**Expected**: `Query.findAll [ Selector.class "a" ] >> Query.index 3` should fail because there are only three results from the `findAll`
**Actual**: `Query.findAll [ Selector.class "a" ] >> Query.index 3` returns the first `div.a`

### PR DESCRIPTION
**Pull request by stoeffel**
resolves #45 

## What changed?

* don't wrap index around if it's too high or to low.
* adds extensive tests for `index`.

### CODE REVIEW

File: tests/Queries.elm [hunk 1]
```diff
@@ -206,21 +207,61 @@ testFirst output =
...
+                        |> Query.hasNot [ tag "div" ]
+            , fuzz (Fuzz.intRange 1 2) "too high" <|
+                \index ->
+                    output
+                        |> Query.findAll []
+                        |> Query.index index
+                        |> Query.hasNot [ tag "div" ]
+            ]
+        , describe "only 3 element"
+            [ fuzz (Fuzz.intRange -3 2) "matches" <|
```
Comment (stoeffel) [inline tests/Queries.elm]: @rtfeldman is there a way to write a test for a list of values? e.g. there is no need for fuzzing if you know all the values you wanna test, right?

```elm
testFor [-3, -2, -1, 0, 1, 2] "matches" <|
  \index ->
-- or
testFor (List.range -3 2) "matches" <|
  \index ->
```

File: src/Test/Html/Query/Internal.elm [hunk 2]
```diff
@@ -237,8 +237,14 @@ getElementAt index list =
...
     in
-    -- Avoid attempting % 0
-    if length == 0 then
+    if
+        -- Avoid attempting % 0
+        (length == 0)
+            -- don't wrap around if index is too high
+            || (index >= length)
+            -- don't wrap around if index is too low
+            || (index < 0 && abs index > length)
```
Comment (eeue56) [inline src/Test/Html/Query/Internal.elm]: 👍

File: tests/Queries.elm [hunk 3]
```diff
@@ -206,21 +207,61 @@ testFirst output =
 testIndex : Single msg -> Test
 testIndex output =
     describe "Query.index"
-        [ describe "Query.index 0" <|
-            [ test "sees it's a <div class='container'>" <|
-                \() ->
+        [ describe "only 1 element"
+            [ fuzz (Fuzz.intRange -1 0) "matches" <|
```
Comment (eeue56) [inline tests/Queries.elm]: I'm not sure if there's any point in this being a fuzz test

Comment (stoeffel) [reply tests/Queries.elm]: yes, your right, it's just less duplication and I was lazy. Will cleanup. I would love to have something like `testValues [-1, 0] ...` see my other comment.

File: src/Test/Html/Query.elm [hunk 4]
```diff
@@ -271,7 +271,7 @@ first (Internal.Multiple showTrace query) =
 `Query.index 0` would match the first element, and `Query.index 1` would match
 the second element.
 
-You can pass negative numbers to "wrap around" - for example, `Query.index -1`
+You can pass negative numbers to get elements from the end - for example, `Query.index -1`
 will match the last element, and `Query.index -2` will match the second-to-last.
 
 If the index falls outside the bounds of the match, the test will fail.
```
Comment (eeue56) [inline src/Test/Html/Query.elm]: Some examples here would go a long way I think

File: tests/Queries.elm [hunk 5]
```diff
@@ -206,21 +206,81 @@ testFirst output =
...
+                        |> Query.index 1
+                        |> Query.hasNot [ tag "div" ]
+            ]
+        , describe "3 element"
+            [ test "index 0 matches" <|
+                \() ->
+                    output
+                        |> Query.findAll [ tag "a" ]
+                        |> Query.index 0
+                        |> Query.has [ tag "a", text "home" ]
```
Comment (eeue56) [inline tests/Queries.elm]: I guess you could make something like `expectLink : Int -> String -> Expectation`

**Comment by stoeffel** [comment]
> Are there any changes that we want to group with this one?

probably, will get back to you and think about it. also cc @avh4

**Comment by avh4** [comment]
If it's known what the cause of https://github.com/eeue56/elm-html-test/issues/13 is, that would be nice to get included.  (There's also https://github.com/eeue56/elm-html-test/issues/32, but I'm assuming that's still a long ways off to address.)

Also, FYI we have a hackday tomorrow, so maybe wait and see if anyone works on elm-test PRs for that (though there aren't any specific plans for that that I know of).

**Comment by stoeffel** [comment]
I might spend some time on elm-html-test tomorrow during hackday actually.

**Comment by rtfeldman** [comment]
I'm merging this with the understanding that we shouldn't publish it until the next `MAJOR` change.

Probably https://github.com/eeue56/elm-html-test/issues/13 is in the same boat with regards to being a bugfix that'd be nice to include in a `MAJOR` change because of the chance it causes previously-passing tests to fail. 😄
